chatroom/urls.py
app_name = 'chatroom'
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('',views.home, name='home'),
  path('signup',views.signup_user, name='signup'),
  path('login',views.login_user, name='login'),
  path('logout',views.logout_user, name='logout'),
  path('create-channel',views.channel_create, name='channel_create'),
  path('search',views.search, name='search'),
  path('channel/join/<slug:slug>',views.join_channel, name='join_channel'),
  path('channel/leave/<slug:slug>',views.leave_channel, name='leave_channel'),
  path('channel/<slug:slug>',views.channel_detail, name='channel_detail'),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
  path('social-auth', include('social_django.urls', namespace='social')),
    path('', include('chatroom.urls', namespace='chatroom')),
]

chatroom/models.py
from django.db import models
from django.urls import reverse;
from django.contrib.auth.models import User

# Create your models here.

class Member(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='member')
  photo = models.ImageField(blank=True, null=True )
  def __str__(self):
    return self.user.username

class Channel(models.Model):
  title = models.CharField(max_length=100)
  slug = models.SlugField(max_length=200,unique=True)
  desc = models.CharField(max_length=250)
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='channels_created', null=True)

  channel_pic = models.ImageField(blank=True, null=True)
  members = models.ManyToManyField(Member, related_name='channels', blank=True)
  def image_url(self):
    if self.channel_pic and hasattr(self.channel_pic, 'url'):
      return self.channel_pic.url
    else:
      return '/static/chatroom/temp-images/no_image.png'
      
  def get_absolute_url(self):
    return reverse('chatroom:channel_detail', args=[self.slug])
  def __str__(self):
    return self.title
  def channel_abv(self):
    abv = ''
    slug=str(self.slug)
    slug_split = slug.split('-')
    for x in slug_split:
      abv+=x[0]
    return abv[:2]
      

class Message(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_messages')
  channel = models.ForeignKey(Channel, on_delete=models.CASCADE, related_name='channel_messages')
  text = models.CharField(max_length=250)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.author.username
    
  class Meta:
    ordering=['created']
  

chatroom/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Message, Channel

class LoginForm(forms.Form):
  username = forms.CharField()
  password = forms.CharField( widget=forms.PasswordInput() )
  
class SignUpForm(UserCreationForm):
  email = forms.EmailField(max_length=254, required=True, help_text='Required. Enter a valid email address.')
  class Meta:
    model=User
    fields = ('username', 'password1','password2' ,'email',)
class MessageForm(forms.ModelForm):
  class Meta:
    model = Message
    fields = ('text',)
    widgets = {'text':forms.Textarea(attrs={'placeholder':'Type a message here', 'id':'message', 'autocomplete':'off', 'rows':'1', 'oninput':'auto_grow(this)' }) }
    
class ChannelForm(forms.ModelForm):
  class Meta:
    model = Channel
    fields = ('title', 'desc',)
    labels = {
      'title': 'Title',
      'desc':'Description',
    }

class SearchForm(forms.Form):
  search_term = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Type a message here'}))
    

chatroom/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import Channel, Member, Message
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, LoginForm,MessageForm, ChannelForm, SearchForm
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your views here.


def signup_user(req):

    if req.method == 'POST':
        form = SignUpForm(req.POST)
        if form.is_valid():
          try:
            new_user = form.save()
            new_member = Member(user=new_user)
            new_member.save()
            return redirect('chatroom:login')
          except:
            messages.error(req, 'Something went wrong try again')
    else:
        form = SignUpForm()
    context = {'form': form, 'refer_to': 'signup', 'title': 'Sign Up'}

    return render(req, 'chatroom/parts/modal.html', context)


def logout_user(req):
    logout(req)
    return redirect('chatroom:login')


def login_user(req):
    if req.method == 'POST':
        form = LoginForm(req.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(req, username=username, password=password)
            if user is not None:
                login(req, user)
                return redirect('chatroom:home')
            else:
                messages.error(req, 'wrong username or password')

        else:
            messages.error(req, 'something went wrong, try again')

    else:
        form = LoginForm()

    context = {'form': form, 'refer_to': 'login', 'title': 'Log In'}

    return render(req, 'chatroom/parts/modal.html', context)

  
@login_required
def search(req):
  if req.method == 'GET':
    search_term=req.GET.get('search')
    search_form = SearchForm(data={'search_term':search_term})
    if search_form.is_valid():
      search_term=search_form.cleaned_data['search_term']
      # search_result = Channel.objects.filter( Q(desc__icontains=search_term))
      search_result = Channel.objects.filter(Q(title__icontains=search_term) | Q(desc__icontains=search_term))
      user_channel_list = req.user.member.channels.all()
      channel_list = Channel.objects.exclude(id__in=user_channel_list)
      context = {
        'previous': False,
        'channel_title': 'Search',
        'search_result': search_result,
        'search_term': search_term,
        'user_channel_list': user_channel_list,
        'channel_list': channel_list,
        }
      return render(req, 'chatroom/parts/search.html', {'context': context})
  return redirect('chatroom:home')
    
# | Q(channel_messages__text__icontains=search_term) 

  
@login_required
def channel_create(req):
    if req.method == 'POST':
      user= req.user
      member = Member.objects.get(user=user)
      form = ChannelForm(req.POST)
      if form.is_valid():
        form_instance = form.save(commit=False)
        form_instance.created_by = user
        form_instance.slug = slugify(form_instance.title)
        form_instance.save()
        form_instance.members.add(member)
        return redirect(form_instance)
      else:
          messages.error(req, 'something went wrong')
          return redirect('chatroom:home')

    else:
      return redirect('chatroom:home')


@login_required
def home(req):
    # user_id = req.user.id
    username = req.user.get_username()
    user_obj = User.objects.get(username=username)
    user_channel_list = user_obj.member.channels.all()
    channel_list = Channel.objects.exclude(id__in=user_channel_list)
    new_channel_form = ChannelForm()
    context = {
        'previous': False,
        'channel_title': 'Channels',
        'channel_list': channel_list,
        'user_channel_list': user_channel_list,
      'new_channel_form':new_channel_form
    }
    return render(req, 'chatroom/parts/home.html', {'context': context})

  
@login_required
def join_channel(req, slug):
  channel = Channel.objects.get(slug=slug)
  if req.user.member not in channel.members.all():
    channel.members.add(req.user.member)
    return redirect(channel)
  else:
    return redirect('chatroom:home')
  
@login_required
def leave_channel(req, slug):
  channel = Channel.objects.get(slug=slug)
  if req.user.member in channel.members.all():
    channel.members.remove(req.user.member)
    return redirect('chatroom:home')


@login_required
def channel_detail(req, slug):
  channel = Channel.objects.get(slug=slug)
  if req.user.member in channel.members.all():
    msg_form = MessageForm()
    context = {
        'previous': True,
        'channel_title': 'All Channels',
        'channel': channel,
        'msg_form': msg_form
    }
    return render(req, 'chatroom/parts/channel_detail.html', {'context': context})
  else:
    return redirect('chatroom:home')
    

chatroom/templates/chatroom/parts/channel_detail.html
{% extends '../base.html' %}
{% load static %}
  
{% block sidebar %}

<div id="sidebar">
      <div id="sidebar-top">
        {% if context.previous %}
        <a href="{% url 'chatroom:home' %}"> &#60;&#60;</a>
        {% else %}
        {% endif %}
        <span id="channels-link"><a href="{% url 'chatroom:home' %}">{{ context.channel_title }}</a></span>
        <span id="cancel-menu">x</span>
      </div>
      <div id="sidebar-middle">
          <span class="sidebar-channel-title">{{ context.channel.title }} </span>
          <p class="sidebar-channel-desc">{{ context.channel.desc }}</p>
          <span class="channel-members-heading">Members:</span>
        <div id="channel-list">
          {% for member in context.channel.members.all %}
          <a href="" class="channel-item">
              <div class="chat-item-dp">
            <img src="{{ member.photo.url }}" alt="" />
          </div>
            <div class="channel-item-member-name">
              {{member.user.username}}
            </div>
          </a>
          {% empty %}
          <span>No members yet</span>
          {% endfor %}
        </div>
      </div> 
      {% include './sidebar_bottom.html' %}
    </div>

{% endblock %}
  
{% block main %}

<div id="main">
      <div id="main-top">
        <img src="{% static 'chatroom/temp-images/menu-solid.svg' %}" alt="" id="menu-icon">
        <p id="channel-title ">{{ context.channel.title }}</p>
      </div>
      {% if messages%}
        <ul>
        {% for msg in messages %}
        <li {% if msg.tags %} class='{{ msg.tags }}'{% endif %}>
          {{msg}}
        </li>
        {% endfor %}
          </ul>
        {% else %}
        <p></p>
      {% endif %}
      <div id="main-middle-chat">
        {% for msg in context.channel.channel_messages.all %}
        <div class="chat-item">
          <div class="chat-item-dp">
            {% if msg.author.member.photo.url %}
            <img src="{{ msg.author.member.photo.url }}" alt="" id="sidebar-dp"/>
        {% else %}
        <img src="{% static 'chatroom/temp-images/no_images.png' %}" alt="" id="sidebar-dp" />
        {% endif %}
          </div>
          <div class="chat-item-right">
            <div class="chat-item-desc">
              <span>{{ msg.author.username }}</span>
              <span>{{ msg.created | date:"H:i" }} &middot; {{ msg.created | date:"m M Y" }}</span>
            </div>
            <div class="chat-text">
              <p>
                {{ msg.text | linebreaks }}
              </p>
            </div>
          </div>
        </div>
        {% empty %}
        <span class="info">no messages here</span>
        {% endfor %}
        
      </div>
      <div id="main-bottom">
        <form action="" method="post" id="message-bar">
          {% csrf_token %}
          {{ context.msg_form.text }}
          <button><img src="{% static 'chatroom/temp-images/send-solid.svg' %}" alt="" /> </button>
        </form>
      </div>
    </div>
<script>
  const messageBox = document.querySelector("#message");
  function auto_grow(element) {
    element.style.height = "auto";
    element.style.height = (element.scrollHeight)+"px";
  };
  const room_name = "{{ context.channel.slug }}" ;
  const username = "{{request.user.username}}";
  const chatSocket = new WebSocket( 'wss://' + window.location.host + '/ws/chat/' + room_name + '/'
        );
  chatSocket.onmessage = (e)=> {
    const dataContainer = JSON.parse(e.data);
    const data = dataContainer.msg_container
    const chatThread = document.querySelector('#main-middle-chat')
    chatThread.innerHTML += (`<div class="chat-item" >
          <div class="chat-item-dp">
        <img src="${data.author_photo_url} " alt="" id="sidebar-dp" />
          </div>
          <div class="chat-item-right">
            <div class="chat-item-desc">
              <span>${ data.username }</span>
              <span>${ data.msg_time } &middot; ${data.msg_date }</span>
            </div>
            <div class="chat-text">
              <p>
                ${ data.message.replace(/\n/g, '<br>\n')}
              </p>
            </div>
          </div>
        </div>`);
    
  };
  chatSocket.onclose = function(e) {
    console.error('Chat socket closed unexpectedly');
  };
  x = document.querySelector('#message-bar')
  x.onsubmit = (event) => {
    event.preventDefault()
    messageBox.style.height = 'auto';
    const messageInputDom = document.querySelector('#message');
    const message = messageInputDom.value;
    chatSocket.send(JSON.stringify({
        'message': message,
        'channel-slug':room_name,
        'username':username,
    }));
    messageInputDom.value = '';
      };
</script>
{% endblock %}

chatroom/templates/chatroom/parts/home.html
{% extends '../base.html' %}
{% load static %}

{% block modal %}

  <div id="modal">
    <div class="create-channel-container">
      <span id="cancel-modal">x</span>
      <span id="create-channel-heading">Create New Channel</span>
      {% if messages%}
<ul>
{% for msg in messages %}
<li {% if msg.tags %} class='{{ msg.tags }}'{% endif %}>
  {{msg}}
</li>
{% endfor %}
  </ul>
{% else %}
<p></p>
{% endif %}
      <form action="{% url 'chatroom:channel_create' %}" method="post">
        {% csrf_token %}
      {% for field in context.new_channel_form %}
        {{ field.label_tag }}
        <ul>
        {% for error in field.errors %}
        <li class='error'>{{error}} </li>
        {% endfor %}
          </ul>
        {{ field }}
        {% endfor  %}
        <button id="create-channel-save">Create</button>
      </form>
    </div>
  </div>
{% endblock %}
  
{% block sidebar %}

<div id="sidebar">
      <div id="sidebar-top">
        {% if context.previous %}
        <a href=""> &#60;&#60;</a>
        {% else %}
        {% endif %}
        <span id="channels-link"><a href="">{{context.channel_title}}</a></span>
        <span id="add-channel">&#43;</span>
        <span id="cancel-menu">x</span>
      </div>
      <div id="sidebar-middle">
        <div id="search">
          <form action="{% url 'chatroom:search' %}" >
            {% csrf_token %}
            <img src="{% static 'chatroom/temp-images/search.svg' %}" alt="" id="search-icon" />
            <input type="search" name="search" id="search-input" placeholder="Search">
            </input>
          </form>
        </div>
        <div id="channel-list">
         <span class="channel-list-title">Your Channels</span>
          {% for y in context.user_channel_list %}
          <a href="{{ y.get_absolute_url }}" class="channel-item">
            <div class="channel-item-no">
              {{y.channel_abv}}
            </div>
            <div class="channel-item-name">
              {{y.title}}
            </div>
          </a>
          {% empty %}
          <span>You've not joined any channel yet</span>
          {% endfor %}
        </div>
        <div id="channel-list">
          <span class="channel-list-title">Recommended</span>
          {% for x in context.channel_list %}
          <a href="{{ x.get_absolute_url }}" class="channel-item">
            <div class="channel-item-no">
              {{x.channel_abv}}
            </div>
            <div class="channel-item-name">
              {{x.title}}
            </div>
          </a>
          {% endfor %}
        </div>
      </div>
      {% include './sidebar_bottom.html' %}
    </div>

{% endblock %}
  
{% block main %}

<div id="main">
      <div id="main-top">
        <img src="{% static 'chatroom/temp-images/menu-solid.svg' %}" alt="" id="menu-icon">
        <p>Home</p>
      </div>
      <div id="main-middle" ">
        <h3 class="channel-listing-heading">Your Channels:</h3>
        {% for x in context.user_channel_list %}
        
        <div class="channel-listing-item">
          <div class="channel-listing-item-dp" >
            <a href="{{x.get_absolute_url}}" target="_self">
            <img src="{{ x.image_url }}" alt="" /> </a>
          </div>
          <div class="channel-listing-item-right">
            <div class="channel-listing-item-title">
              <a href="{{x.get_absolute_url}}" target="_self">{{ x.title }}</a>
            </div>
            <div class="channel-listing-item-desc">
              <p>
                {{ x.desc | truncatewords:20  }}
              </p>
            </div>
            <div class="channel-listing-item-cta">
              <a href="{% url 'chatroom:leave_channel' x.slug %}">
                Leave
              </a>
            </div>
          </div>
        </div>
          
        {% endfor %}
        
        <h3 class="channel-listing-heading">Recommended:</h3>
        {% for x in context.channel_list %}
        <div class="channel-listing-item">
          <div class="channel-listing-item-dp" >
            <a href="{{x.get_absolute_url}}" target="_self">
            <img src="{{ x.image_url }}" alt="" /> </a>
          </div>
          <div class="channel-listing-item-right">
            <div class="channel-listing-item-title">
              <a href="{{x.get_absolute_url}}" target="_self">{{ x.title }}</a>
            </div>
            <div class="channel-listing-item-desc">
              <p>
                {{ x.desc | truncatewords:20  }}
              </p>
            </div>
            <div class="channel-listing-item-cta">
              <a href="{% url 'chatroom:join_channel' x.slug %}">
                Join
              </a>
            </div>
          </div>
        </div>
          
        {% endfor %}
      </div>
    </div>

{% endblock %}

chatroom/templates/chatroom/parts/modal.html
 {% extends '../base.html' %}


{% block modal %}
<div id="modal" style="display:flex">
    <div class="create-channel-container">
      
      <h2 id="create-channel-heading">{{title}}</h2>
      {% if messages%}
<ul>
{% for msg in messages %}
<li {% if msg.tags %} class='{{ msg.tags }}'{% endif %}>
  {{msg}}
</li>
{% endfor %}
  </ul>
{% else %}
<p></p>
{% endif %}
      <span id="cancel-modal">x</span>
      <form action="" method="post">
        {% csrf_token %}
      {% for field in form %}
        {{ field.label_tag }}
        <ul>
        {% for error in field.errors %}
        <li class='error'>{{error}} </li>
        {% endfor %}
          </ul>
        {{ field }}
        {% endfor  %}
        <button id="create-channel-save">{{title}}</button>
      </form>
    </div>
  </div>
 
{% endblock %}

chatroom/templates/chatroom/parts/search.html
{% extends '../base.html' %}
{% load static %}

{% block modal %}

  <div id="modal">
    <div class="create-channel-container">
      <span id="cancel-modal">x</span>
      <span id="create-channel-heading">Create New Channel</span>
      {% if messages%}
<ul>
{% for msg in messages %}
<li {% if msg.tags %} class='{{ msg.tags }}'{% endif %}>
  {{msg}}
</li>
{% endfor %}
  </ul>
{% else %}
<p></p>
{% endif %}
      <form action="{% url 'chatroom:channel_create' %}" method="post">
        {% csrf_token %}
      {% for field in context.new_channel_form %}
        {{ field.label_tag }}
        <ul>
        {% for error in field.errors %}
        <li class='error'>{{error}} </li>
        {% endfor %}
          </ul>
        {{ field }}
        {% endfor  %}
        <button id="create-channel-save">Create</button>
      </form>
    </div>
  </div>
{% endblock %}
  
{% block sidebar %}

<div id="sidebar">
      <div id="sidebar-top">
        {% if context.previous %}
        <a href=""> &#60;&#60;</a>
        {% else %}
        {% endif %}
        <a href="{% url 'chatroom:home' %}">&#60;&#60;</a>
        <span id="channels-link"><a href="{% url 'chatroom:home' %}">Home</a></span>
        <span id="add-channel">&#43;</span>
        
        <span id="cancel-menu">x</span>
      </div>
      <div id="sidebar-middle">
        <div id="search">
          <form action="{% url 'chatroom:search' %}" >
            {% csrf_token %}
            <img src="{% static 'chatroom/temp-images/search.svg' %}" alt="" id="search-icon" />
            <input type="search" name="search" id="search-input" placeholder="Search">
            </input>
          </form>
        </div>
        <div id="channel-list">
         <span class="channel-list-title">Your Channels:</span>
          {% for y in context.user_channel_list %}
          <a href="{{ y.get_absolute_url }}" class="channel-item">
            <div class="channel-item-no">
              {{y.channel_abv}}
            </div>
            <div class="channel-item-name">
              {{y.title}}
            </div>
          </a>
          {% empty %}
          <span>You've not joined any channel yet</span>
          {% endfor %}
        </div>
        <div id="channel-list">
          <span class="channel-list-title">Recommended</span>
          {% for x in context.channel_list %}
          <a href="{{ x.get_absolute_url }}" class="channel-item">
            <div class="channel-item-no">
              {{x.channel_abv}}
            </div>
            <div class="channel-item-name">
              {{x.title}}
            </div>
          </a>
          {% empty %}
          <span>Sorry no match was found</span>
          {% endfor %}
        </div>
      </div>
      {% include './sidebar_bottom.html' %}
    </div>

{% endblock %}
  
{% block main %}

<div id="main">
      <div id="main-top">
        <img src="{% static 'chatroom/temp-images/menu-solid.svg' %}" alt="" id="menu-icon">
        <p>Search</p>
      </div>
      <div id="main-middle" ">
        <h3 class="channel-listing-heading">Search results for "{{ context.search_term }}"</h3>
        {% for x in context.search_result %}
        
        <div class="channel-listing-item">
          <div class="channel-listing-item-dp" >
            <a href="{{x.get_absolute_url}}" target="_self">
            <img src="{{ x.image_url }}" alt="" /> </a>
          </div>
          <div class="channel-listing-item-right">
            <div class="channel-listing-item-title">
              <a href="{{x.get_absolute_url}}" target="_self">{{ x.title }}</a>
            </div>
            <div class="channel-listing-item-desc">
              <p>
                {{ x.desc | truncatewords:20  }}
              </p>
            </div>
            <div class="channel-listing-item-cta">
              <a href="">
                Join
              </a>
            </div>
          </div>
        </div>
          
        {% empty %}
        <span>Sorry no match was found</span>
        {% endfor %}
      </div>
    </div>

{% endblock %}

chatroom/templates/chatroom/parts/sidebar_bottom.html
{% load static %}
<div id="sidebar-bottom">
        {% if request.user.member.photo.url %}
        <img src="{{request.user.member.photo.url}}" alt="" id="sidebar-dp" />
        {% else %}
        <img src="{% static 'chatroom/temp-images/no_images.png' %}" alt="" id="sidebar-dp" />
        {% endif %}
        <div id="sidebar-extra">
          <p id="sidebar-display-name">
            {{request.user.username}}
          </p>
          <!-- <div class="sidebar-expandable-container"> -->

          <span id="sidebar-bottom-expander">
            <img src="{% static 'chatroom/temp-images/down-arrow.svg' %}" alt="" id="sidebar-bottom-expander-icon">
            <div id="sidebar-expandable">
              <a href="" class="sidebar-expandable-item">
                <img src="{% static 'chatroom/temp-images/account-profile-circle.svg' %}" alt="" />
                <p>Profile</p>
              </a>
              <a href="" class="sidebar-expandable-item">
                <img src="{% static 'chatroom/temp-images/waving_hand.svg' %}" alt="" />
                <p>Tweeter</p>
              </a>
              <hr />
              <a href="{% url 'chatroom:logout' %}" class="sidebar-expandable-item logout">
                <img src="{% static 'chatroom/temp-images/logout.svg' %}" alt="" />
                <p>Logout</p>
              </a>
            </div>
          </span>
          <!-- </div> -->

        </div>
      </div>